version: '3.7'

services:
  app:
    build: .
    ports:
    - 8080:80
    volumes:
    - .:/var/www/html
    depends_on:
    - mysql
  mysql:
    image: mariadb:10.3
    volumes:
    - db:/var/lib/mysql
    - ./randy/database:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:3306

volumes:
  db:
