<link rel="stylesheet" href="css/style.css">
<nav role="navigation">
    <div id="menuToggle">
        <input type="checkbox" />
        <span></span>
        <span></span>
        <span></span>
        <ul id="menu">
            <img src="images/logo.png"  width="256" height="256">
            <a href="index.php"><li>Home</li></a>
            <a href="about.php"><li>About</li></a>
            <a href="login.php"><li>Login</li></a>
        </ul>
    </div>
</nav>